# Generated by Django 3.2.22 on 2023-10-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_user'),
        ('users', '0002_usercustom_user_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='thumbnail_sizes',
            field=models.ManyToManyField(to='api.ThumbnailSize'),
        ),
    ]
