# Generated by Django 3.2.22 on 2023-10-11 08:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
                ('expires_in', models.IntegerField()),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expiring_link', to='api.image')),
            ],
        ),
    ]
